### ISSUE TITLE
Minting URIs

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#29]
@nathangibson Should I use this spreadsheet for assigning new work URIs for the corpus? If so, how much info should I fill in?
https://docs.google.com/spreadsheets/d/1d8gxz-Ax7bozQeAzy7ufzSjUn0z9muNHIi910A0gcuw/edit#gid=0

**Comment by nathangibson** [comment]
Yes, please. 

Feel free to create new tabs in order to group however you would like. 

Since we will use the info you enter to create the records in NHSL, ideally the info would include at least the following:
 - English and Syriac titles for NHSL (in columns "title syriaca-headword.Edition 1.en" and "title syriaca-headword.Edition 1.syr"). You are welcome to choose what you think is an appropriate standard title, and I will check back with you if I have suggested changes.
 - Author URI (in "author ref.Edition 1"). If the author doesn't exist, let me know and we can create a new record.
 - Syriaca.org bibl URI or Zotero ID of the edition transcribed for the Syriac Corpus (in "Edition 2")
 - Vols/pgs from transcribed edition (in "citedRange vol.Edition 2"/"citedRange pp.Edition 2") (if you have them).
 - When the work is part of a larger work, the URI of the larger work (in "relation dct---isPartOf.Edition 1")

*You* are the editor of these records in NHSL, so if you want to include other stuff, let me know and we can add the columns you need.

**Comment by jedwardwalters** [comment]
Great. Thanks for all of this, @nathangibson. Mostly I just wanted to be sure I wasn't about to start inputing the data in the wrong place!

**Comment by jedwardwalters** [comment]
@nathangibson What should we do for the source bibl if the text comes from a manuscript, not a printed edition?

**Comment by nathangibson** [comment]
@jedwardwalters I've added a few more columns with instructions (MS 1, etc.). You can continue to add columns as needed according to this pattern. Note that information coming from the manuscript (titles, etc.) should be in a different column from info coming from an edition. I've also added the column "witnesses.Edition 1" where you can put which column contains the id of the transcribed text (Edition 2 or MS 1, etc.). Let me know whether this makes sense.

**Comment by jedwardwalters** [comment]
Thanks!
