### ISSUE TITLE
New bibl item

### ISSUE THREAD

**Issue by jedwardwalters** [srophe/syriac-corpus#78]
@nathangibson Can we add a new bibl item for Charlesworth's edition of the Odes of Solomon so I can put it in the header? I created a record in the Zotero group:
https://www.zotero.org/groups/syriaca.org_test_bibliography_module/items/itemKey/2F8KPCSU

**Comment by nathangibson** [comment]
I’m working on this today, since I am also exporting some other items from Zotero.

**Comment by nathangibson** [comment]
Here you go: http://syriaca.org/bibl/2455

**Comment by jedwardwalters** [comment]
Thanks! Also, is this the best way to request new bibl items whenever this comes up?

**Comment by nathangibson** [comment]
Yes, this is fine. Two things that will make it easier, though: (1) If you put new items in the "BYU Corpus" subfolder and (2) if you assign a unique numbered tag (functions as an ID, you can open the tag pane when you are on the top-level folder in order to see what the next number would be). 

Then when I export I move them to "BYU Corpus - EXPORTED". 

It's also easiest to do them in a batch. If you need placeholders in the meantime, you can use the Zotero ID (the unique number tag) as an idno and then do a find-replace later to insert the real URI. E.g., `<idno type="zotero">1041</idno>`. Make sense?

**Comment by jedwardwalters** [comment]
Yep, that's great. Thanks!
